Profile page
cepave-f2e/owl-light pull request #2
Opened 2016-12-08 02:25 UTC by CApopsicle

`/profile` page

<img width="1277" alt="2016-12-08 10 22 54" src="https://cloud.githubusercontent.com/assets/5334755/20995207/7046a474-bd30-11e6-99d2-f19d566b6488.png">

<img width="1277" alt="2016-12-08 10 23 02" src="https://cloud.githubusercontent.com/assets/5334755/20995208/7084a2b0-bd30-11e6-9221-2c2d57600760.png">

cc @rwu823 @chuanxd

2016-12-08 02:26 UTC, chuanxd requested changes

2016-12-08 02:26 UTC, chuanxd commented on src/app.scss
> +  margin: 0
我等等 加個 css reset 還有 global 的 PR

2016-12-08 02:28 UTC, chuanxd commented on index.html
> +  <body style="background:#e6ebf0">
這不用加，原本 background 只是一個範例

2016-12-08 02:29 UTC, CApopsicle commented on src/app.scss
> +  margin: 0
👌

2016-12-08 02:44 UTC, CApopsicle commented on src/app.scss
> +  margin: 0
已修改！

2016-12-08 02:44 UTC, CApopsicle commented on index.html
> +  <body style="background:#e6ebf0">
已修改！

2016-12-08 06:55 UTC, chuanxd commented on src/containers/profile/profile.scss
> +div[data-role='tab-content'][data-selected='1'] {
這個還需要嗎？

2016-12-08 08:39 UTC, CApopsicle commented on src/containers/profile/profile.scss
> +div[data-role='tab-content'][data-selected='1'] {
恩恩 這是讓 `tab-contant` 置中的

2016-12-08 08:41 UTC, chuanxd commented on src/containers/profile/profile.scss
> +div[data-role='tab-content'][data-selected='1'] {
這樣我們現在全部頁面都會重複寫到耶

2016-12-08 09:35 UTC, chuanxd commented on src/containers/profile/profile.scss
> +div[data-role='tab-content'][data-selected='1'] {
我剛看現在元件應該是不需要了吧？ @CApopsicle

2016-12-08 10:40 UTC, CApopsicle commented on src/containers/profile/profile.scss
> +div[data-role='tab-content'][data-selected='1'] {
可是不寫的話..預設是會靠左
會影響到別頁的Tab的話 那還要再想一下用什麼方法置中QQ

2016-12-09 08:11 UTC, CApopsicle commented on src/containers/profile/profile.scss
> +div[data-role='tab-content'][data-selected='1'] {
已修改！

2016-12-09 10:30 UTC, CApopsicle commented
已改成英文!

2016-12-12 03:02 UTC, chuanxd approved these changes
LGTM

2016-12-12 03:02 UTC, merged