Login & Signup
cepave-f2e/owl-light pull request #28
Opened 2016-12-29 02:34 UTC by CApopsicle

url: `/login`
login page
![login page](https://cloud.githubusercontent.com/assets/5334755/21535592/31d965fe-cdb2-11e6-8c44-271876e1bf9c.png)

url: `signup`
signup page
![signup page](https://cloud.githubusercontent.com/assets/5334755/21535597/3eee5b46-cdb2-11e6-8970-743da8fe74d5.png)

2017-01-03 10:27 UTC, rwu823 commented on src/store/signup/mutations.js
> +    }, 2000)
2秒的意思是 QQ?

2017-01-03 10:27 UTC, rwu823 commented on src/store/login/mutations.js
> +    }, 2000)
2秒的意思是 QQ?

2017-01-03 10:38 UTC, CApopsicle commented on src/store/signup/mutations.js
> +    }, 2000)
signup成功之後顯示notification然後2秒後跳到 `/login` page

![signup page-success](https://cloud.githubusercontent.com/assets/5334755/21605362/bdc7d7fa-d1e3-11e6-8eda-bb97277715df.png)

2017-01-03 10:39 UTC, CApopsicle commented on src/store/login/mutations.js
> +    }, 2000)
同上

2017-01-03 11:41 UTC, rwu823 requested changes

2017-01-03 11:41 UTC, rwu823 commented on src/store/login/mutations.js
> +  'login/login.success'(state, { data, router }) {
同使用 `namespaces: true`

2017-01-04 02:18 UTC, rwu823 requested changes

2017-01-04 02:18 UTC, rwu823 commented on src/store/login/actions.js
> +      commit('login/login.fail', {
namespaced

2017-01-04 02:18 UTC, rwu823 commented on src/store/login/actions.js
> +      commit('login/login.success', {
namespaced

2017-01-04 02:46 UTC, CApopsicle commented on src/store/login/mutations.js
> +  'login/login.success'(state, { data, router }) {
fixed!

2017-01-04 02:46 UTC, CApopsicle commented on src/store/login/actions.js
> +      commit('login/login.success', {
fixed!

2017-01-04 02:46 UTC, CApopsicle commented on src/store/login/actions.js
> +      commit('login/login.fail', {
fixed!

2017-01-05 06:33 UTC, chuanxd commented on src/store/login/mutations.js
> +    }, 2000)
我覺得可以適時的寫註解^^

2017-01-05 08:49 UTC, rwu823 commented
rebase pleas

2017-01-05 08:49 UTC, rwu823 approved these changes

2017-01-05 08:50 UTC, merged