Profile page
cepave-f2e/owl-light pull request #29
Opened 2016-12-29 03:00 UTC by CApopsicle

profile page

![profile-profile](https://cloud.githubusercontent.com/assets/5334755/21535832/dc670352-cdb5-11e6-9e8e-3e7972bb7d45.png)

![profile-password](https://cloud.githubusercontent.com/assets/5334755/21535835/e14c2bea-cdb5-11e6-8515-a73e95f3a275.png)

cc @rwu823 @chuanxd

2016-12-29 10:45 UTC, rwu823 requested changes

2016-12-29 10:45 UTC, rwu823 commented on src/containers/profile/index.js
> +        im: this.$refs.im.value || ''
`value` 預設就是空的，應該不需要 `|| ''`？

2016-12-29 10:48 UTC, rwu823 requested changes

2016-12-29 10:48 UTC, rwu823 commented on src/store/profile/mutations.js
> +  'profile/getUserInfo.fail'(state, { err }) {},
設 `namescaped: true` 就不需要每一筆都寫 `profile/` 囉

2016-12-29 10:49 UTC, chuanxd commented on src/store/profile/mutations.js
> +  'profile/getUserInfo.fail'(state, { err }) {},
但是外部 `dispatch, commit` 還是要寫 `/` QQ

2017-01-04 04:12 UTC, CApopsicle commented on src/store/profile/mutations.js
> +  'profile/getUserInfo.fail'(state, { err }) {},
fixed!

2017-01-04 05:32 UTC, CApopsicle commented on src/containers/profile/index.js
> +        im: this.$refs.im.value || ''
fixed!

2017-01-04 23:21 UTC, rwu823 commented on src/containers/profile/index.js
> +      const { userInfo }= this.$store.state.profile
`=` 空格 @@

2017-01-04 23:23 UTC, rwu823 requested changes

2017-01-04 23:23 UTC, rwu823 commented on src/containers/profile/index.js
> +      const { userInfo }= this.$store.state.profile
`=` 空格 @@

2017-01-05 06:47 UTC, CApopsicle commented on src/containers/profile/index.js
> +      const { userInfo }= this.$store.state.profile
fixed!

2017-01-05 08:03 UTC, rwu823 commented
rebase please

2017-01-05 08:04 UTC, rwu823 approved these changes

2017-01-05 08:06 UTC, merged